const propertiesHeader = [
  'agence_id',
  'program_ref',
  'lot_ref',
  'postal',
  'city',
  'country',
  'address',
  'district',
  'heading',
  'description',
  'is_exclusive',
  'available_date',
  'type_of_property',
  'price',
  'fee',
  'surface',
  'land_surface',
  'nb_pieces',
  'nb_rooms',
  'expenses',
  'floor',
  'nb_floors',
  'nb_bathrooms',
  'nb_washrooms',
  'nb_wc',
  'is_separate_wc',
  'heating_type',
  'kitchen_type',
  'south_orientation',
  'east_orientation',
  'west_orientation',
  'north_orientation',
  'nb_balcony',
  'sf_balcony',
  'elevator',
  'cellar',
  'nb_parking',
  'nb_boxes',
  'digicode',
  'intercom',
  'guardian',
  'terrace',
  'picture_1',
  'picture_2',
  'picture_3',
  'picture_4',
  'picture_5',
  'picture_6',
  'picture_7',
  'picture_8',
  'picture_9',
  'picture_10',
  'picture_11',
  'picture_12',
  'picture_13',
  'picture_14',
  'picture_15',
  'picture_16',
  'picture_17',
  'picture_18',
  'picture_19',
  'picture_20',
  'phone',
  'contact',
  'email',
  'energy_consum',
  'energy_balance_consum',
  'ghg_emissions',
  'ghg_balance_emission',
  'Neighborhood_identifier',
  'transport_lines',
  'stations',
  'property_sub_type',
  'file',
  'technical_id',
];

const availableProperties = {
  lot_ref: 'Reference du lot',
  postal: 'Code postal',
  city: 'Ville',
  country: 'Pays',
  address: 'Adresse',
  district: 'Quartier',
  heading: 'Rubrique',
  description: 'Description',
  available_date: 'Date de disponibilité',
  type_of_property: 'Type de propriété',
  price: 'Prix',
  surface: 'Surface',
  land_surface: 'Surface terrain',
  nb_pieces: 'Nombre de pieces',
  nb_rooms: 'Nombre de rooms',
  expenses: 'Dépenses',
  nb_floors: 'Nombre de floors',
  nb_bathrooms: 'Nombre de salles de bains',
  nb_washrooms: 'Nombre de toilettes',
  nb_wc: 'Nombre de wc',
  is_separate_wc: 'WC séparés',
  south_orientation: 'Orientation sud',
  east_orientation: 'Orientation est',
  west_orientation: 'Orientation ouest',
  north_orientation: 'Orientation nord',
  nb_balcony: 'Nombre de balcon',
  elevator: 'ascenseur',
  nb_parking: 'Nombre de parking',
  digicode: 'Digicode',
  intercom: 'Intercom',
  guardian: 'Gardien',
  terrace: 'Terrasse',
  phone: 'Téléphone',
  contact: 'Contacte',
  email: 'E-mail',
  transport_lines: 'lignes',
  stations: 'Stations',
  property_sub_type: 'Sous type de bien',
  file: 'fichier',
};

const filteredProperties = Object.keys(availableProperties);

module.exports = {
  propertiesHeader,
  filteredProperties,
};
