const propertiesHeader = [
  `Identifiant agence`,
  `Référence agence du bien`,
  `Type d’annonce`,
  `typeOfProperty`,
  `postal`,
  `city`,
  `country`,
  `address`,
  `Quartier / Proximité`,
  `Activités commerciales`,
  `price`,
  `Loyer / mois murs`,
  `Loyer CC`,
  `Loyer HT`,
  `Honoraires`,
  `surface`,
  `SF terrain (m²)`,
  `NB de pièces Entier "3" Obligatoire`,
  `NB de chambres Entier "2"`,
  `Libellé`,
  `Description`,
  `available_date`,
  `Charges`,
  `Etage Entier "0" "0" pour Rez -de -chaussée / Rez -de -jardin "1" pour le premier étage Etc…`,
  `NB d’étages Entier "2"`,
  `Meublé`,
  `Année de construction Entier "1985" Champ Numérique`,
  `Refait à neuf`,
  `NB de salles de bain Entier "2"`,
  `NB de salles d’eau Entier "2"`,
  `NB de WC Entier "2"`,
  `is_separate_wc`,
  `Type de chauffage Entier "512" Voir codifications`,
  `Type de cuisine Entier "3" Voir codifications`,
  `Orientation sud`,
  `Orientation est`,
  `Orientation ouest`,
  `Orientation nord`,
  `NB balcons Entier "2"`,
  `SF Balcon`,
  `elevator`,
  `Cave`,
  `NB de parkings Entier ""`,
  `NB de boxes Entier ""`,
  `digicode`,
  `intercom`,
  `gardian`,
  `terrasse`,
  `Prix semaine / basse saison`,
  `Prix quinzaine / basse saison`,
  `Prix mois / basse saison`,
  `Prix semaine / haute saison`,
  `Prix quinzaine / haute saison`,
  `Prix mois / haute saison`,
  `NB de personnes Entier "" Locations vacances : Capacité d’accueil`,
  `Type de résidence`,
  `Situation`,
  `NB de couverts Entier ""`,
  `NB de lits doubles Entier ""`,
  `NB de lits simples Entier ""`,
  `Alarme`,
  `Câble TV`,
  `Calme`,
  `Climatisation`,
  `Piscine`,
  `Aménagement pour Handicapés`,
  `Animaux acceptés`,
  `Cheminée`,
  `Congélateur`,
  `Four`,
  `Lave-vaisselle`,
  `Micro-ondes`,
  `Placards`,
  `phone`,
  `Proche lac`,
  `Proche tennis`,
  `Proche pistes de ski`,
  `Vue dégagée`,
  `Chiffre d’affaire`,
  `Longueur façade (m)`,
  `Publications`,
  `Mandat en exclusivité`,
  `Coup de cœur`,
  `picture_1`,
  `picture_2`,
  `picture_3`,
  `picture_4`,
  `picture_5`,
  `picture_6`,
  `picture_7`,
  `picture_8`,
  `picture_9`,
  `picture_1_title`,
  `picture_2_title`,
  `picture_3_title`,
  `picture_4_title`,
  `picture_5_title`,
  `picture_6_title`,
  `picture_7_title`,
  `picture_8_title`,
  `picture_9_title`,
  `Photo panoramique`,
  `URL visite virtuelle`,
  `Téléphone à afficher`,
  `Contact à afficher`,
  `Email à afficher`,
  `CP Réel du bien`,
  `Ville réelle du bien`,
  `Intercabinet`,
  `Intercabinet prive`,
  `N° de mandat`,
  `Date mandat Date "13/02/2003"`,
  `Nom mandataire`,
  `Prénom mandataire`,
  `Raison sociale mandataire`,
  `Adresse mandataire`,
  `CP mandataire`,
  `Ville mandataire`,
  `Téléphone mandataire`,
  `Commentaires mandataire`,
  `Commentaires privés`,
  `Code négociateur`,
  `Code Langue 1`,
  `Proximité Langue 1`,
  `Libellé Langue 1`,
  `Descriptif Langue 1`,
  `Code Langue 2`,
  `Proximité Langue 2`,
  `Libellé Langue 2`,
  `Descriptif Langue 2`,
  `Code Langue 3`,
  `Proximité Langue 3`,
  `Libellé Langue 3`,
  `Descriptif Langue 3`,
  `customField1 – Dispositif`,
  `customField2 – Neuf / ancien`,
  `customField3 – Type de sol`,
  `customField4 – Videophone`,
  `customField5 – Label BBC`,
  `customField6 – Date Modification Offre`,
  `customField7 – Nombre de garage`,
  `customField8 – Nombre de parking intérieur`,
  `customField9 – Nombre de parking extérieur`,
  `customField10 – Etat façade`,
  `customField11 – Etat partie commune`,
  `customField12 – Résidence sénior`,
  `customField13 – Résidence étudiante`,
  `customField14 – Time Share`,
  `customField15 – Programme Solutions Investisseurs`,
  `customField16 – Circuit commercial`,
  `customField17 – Logement étudiant`,
  `customField18 – Exclu Nexity`,
  `customField19 – collocation interdite`,
  `customField20`,
  `customField21`,
  `customField22`,
  `customField23`,
  `customField24`,
  `customField25`,
  `Dépôt de garantie`,
  `Récent`,
  `Travaux à prévoir`,
  `picture_10`,
  `picture_11`,
  `picture_12`,
  `picture_13`,
  `picture_14`,
  `picture_15`,
  `picture_16`,
  `picture_17`,
  `picture_18`,
  `picture_19`,
  `picture_20`,
  `Consommation énergie Entier "191" Consommation d’énergie en kWhEP/m²/an`,
  `lot_ref`,
  `Bilan consommation énergie`,
  `Emissions GES Entier "42" Estimation des émissions : kg éqCO2/m²/an`,
  `Bilan émission GES`,
  `Identifiant quartier Entier "" Voir identification des quartiers`,
  `property_sub_type`,
  `Périodes de disponibilité`,
  `Périodes basse saison`,
  `Périodes haute saison`,
  `Prix du bouquet`,
  `Rente mensuelle`,
  `Age de l’homme Entier Age de l’homme (Viager)`,
  `Age de la femme Entier Age de la femme (Viager)`,
  `Entrée`,
  `Résidence`,
  `Parquet`,
  `Vis - à -vis`,
  `Transport : Ligne`,
  `Transport : Station`,
  `Durée bail Entier Durée du bail pour les locations`,
  `Places en salle Entier Nombre de places en salle (pour les restaurants par exemple)`,
  `Monte charge`,
  `Quai`,
  `Nombre de bureaux Entier`,
  `Prix du droit d’entrée`,
  `Prix masqué`,
  `Loyer annuel global`,
  `Charges annuelles globales`,
  `Loyer annuel au m2`,
  `Charges annuelles au m2`,
  `Charges mensuelles HT`,
  `Loyer annuel CC`,
  `Loyer annuel HT`,
  `Charges annuelles HT`,
  `Loyer annuel au m2 CC`,
  `Loyer annuel au m2 HT`,
  `Charges annuelles au m2 HT`,
  `Divisible`,
  `Surface divisible minimale`,
  `Surface divisible maximale`,
  `Surface séjour`,
  `Nombre de véhicules Entier "2" (Uniquement parkings)`,
  `Prix du droit au bail`,
  `Valeur à l’achat`,
  `Répartition du chiffre d’affaire`,
  `Terrain agricole`,
  `Equipement bébé`,
  `Terrain constructible`,
  `Résultat Année N-2 Entier "65000" Résultats année N-2 (Uniquement Ventes fond de commerce)`,
  `Résultat Année N-1 Décimal(11,2) "55000" Résultats année N-1 (Uniquement Ventes fond de commerce)`,
  `Résultat Actuel Entier "60000" Résultats année en cours (Uniquement Ventes fond de commerce)`,
  `Immeuble de parkings`,
  `Parking isolé`,
  `Si Viager Vendu Libre`,
  `Logement à disposition`,
  `Terrain en pente`,
  `Plan d’eau`,
  `Lave linge`,
  `Sèche linge`,
  `Connexion internet`,
  `Chiffre affaire Année N-2 Entier "35000" Chiffre d’affaire année N-2`,
  `Chiffre affaire Année N-1 Entier "45000" Chiffre d’affaire année N-1`,
  `Conditions financières`,
  `Prestations diverses`,
  `Longueur façade`,
  `Montant du rapport`,
  `Nature du bail`,
  `Nature bail commercial`,
  `Nombre terrasses Entier "3"`,
  `Prix hors taxes`,
  `Si Salle à manger`,
  `Si Séjour`,
  `Terrain donne sur la rue`,
  `Immeuble de type bureaux`,
  `Terrain viabilisé`,
  `Equipement Vidéo`,
  `Surface de la cave`,
  `Surface de la salle à manger`,
  `Situation commerciale`,
  `Surface maximale d’un bureau`,
  `Honoraires charge acquéreur (obsolète)`,
  `Pourcentage honoraires TTC (obsolète) Décimal(11,2) 3 Evolution 15/03/2017 Remplacé par le champ 15`,
  `En copropriété`,
  `Nombre de lots Entier 10 Evolution 09/07/2014 Nombre de lots dans la copropriété (ALUR)`,
  `Charges annuelles Décimal(11,2) 3500 Evolution 09/07/2014 Montant moyen annuel de la quote-part du budget prévisionnel des dépenses courantes (ALUR)`,
  `Syndicat des copropriétaires en procédure`,
  `Détail procédure du syndicat des copropriétaires`,
  `customField26`,
  `picture_21`,
  `picture_22`,
  `picture_23`,
  `picture_24`,
  `picture_25`,
  `picture_26`,
  `picture_27`,
  `picture_28`,
  `picture_29`,
  `picture_30`,
  `picture_10_title`,
  `picture_11_title`,
  `picture_12_title`,
  `picture_13_title`,
  `picture_14_title`,
  `picture_15_title`,
  `picture_16_title`,
  `picture_17_title`,
  `picture_18_title`,
  `picture_19_title`,
  `picture_20_title`,
  `picture_21_title`,
  `picture_22_title`,
  `picture_23_title`,
  `picture_24_title`,
  `picture_25_title`,
  `picture_26_title`,
  `picture_27_title`,
  `picture_28_title`,
  `picture_29_title`,
  `picture_30_title`,
  `Prix Terrain`,
  `Prix du modèle de Maison`,
  `Nom de l'agence gérant le terrain`,
  `Latitude`,
  `Longitude`,
  `Précision GPS Entier "1" Obligatoire pour la prise en compte des coordonnées Degré de précision des coordonnées GPS (Cf section Précision GPS)`,
  `Version Format`,
  `Honoraires à la charge De Entier "1" - Acquéreur "2" - Vendeur "3" - Acquéreur ET Vendeur (Loi Alur 02/2017) Obligatoire VENTE UNIQUEMENT Spécifie la(les) personne(s) en charge du règlement des honoraires à l’issue de la transaction`,
  `Prix hors honoraires acquéreur`,
  `Modalités charges Locataire Entier "1" - Forfaitaires mensuelles "2" - Prévisionnelles mensuelles avec régularisation annuelle "3"`,
  `Complément loyer`,
  `Part honoraires`,
];

// const propertiesHeader = [
//   'agence_id',
//   'program_ref',
//   'lot_ref',
//   'postal',
//   'city',
//   'country',
//   'address',
//   'district',
//   'heading',
//   'description',
//   'is_exclusive',
//   'available_date',
//   'typeOfProperty',
//   'price',
//   'fee',
//   'surface',
//   'land_surface',
//   'nb_pieces',
//   'nb_rooms',
//   'expenses',
//   'floor',
//   'nb_floors',
//   'nb_bathrooms',
//   'nb_washrooms',
//   'nb_wc',
//   'is_separate_wc',
//   'heating_type',
//   'kitchen_type',
//   'south_orientation',
//   'east_orientation',
//   'west_orientation',
//   'north_orientation',
//   'nb_balcony',
//   'sf_balcony',
//   'elevator',
//   'cellar',
//   'nb_parking',
//   'nb_boxes',
//   'digicode',
//   'intercom',
//   'guardian',
//   'terrace',
//   'picture_1',
//   'picture_2',
//   'picture_3',
//   'picture_4',
//   'picture_5',
//   'picture_6',
//   'picture_7',
//   'picture_8',
//   'picture_9',
//   'picture_10',
//   'picture_11',
//   'picture_12',
//   'picture_13',
//   'picture_14',
//   'picture_15',
//   'picture_16',
//   'picture_17',
//   'picture_18',
//   'picture_19',
//   'picture_20',
//   'phone',
//   'contact',
//   'email',
//   'energy_consum',
//   'energy_balance_consum',
//   'ghg_emissions',
//   'ghg_balance_emission',
//   'Neighborhood_identifier',
//   'transport_lines',
//   'stations',
//   'property_sub_type',
//   'file',
//   'technical_id',
// ];

const availableProperties = {
  lot_ref: 'identifiant technique',
  postal: 'Code postal',
  city: 'Ville', //
  country: 'Pays', //
  address: 'Adresse', //
  district: 'Quartier',
  heading: 'Rubrique',
  description: 'Description',
  available_date: 'Date de disponibilité', //
  typeOfProperty: 'Type de propriété', //
  price: 'Prix', //
  surface: 'Surface', //
  land_surface: 'Surface terrain',
  nb_pieces: 'Nombre de pieces',
  nb_rooms: 'Nombre de rooms',
  expenses: 'Dépenses',
  nb_floors: 'Nombre de floors',
  nb_bathrooms: 'Nombre de salles de bains',
  nb_washrooms: 'Nombre de toilettes',
  nb_wc: 'Nombre de wc',
  is_separate_wc: 'WC séparés', // 1
  south_orientation: 'Orientation sud',
  east_orientation: 'Orientation est',
  west_orientation: 'Orientation ouest',
  north_orientation: 'Orientation nord',
  nb_balcony: 'Nombre de balcon',
  elevator: 'ascenseur', // 1
  nb_parking: 'Nombre de parking',
  digicode: 'Digicode', // 1
  intercom: 'Intercom', // 1
  guardian: 'Gardien', // 1
  terrace: 'Terrasse', // 1
  phone: 'Téléphone', // 1
  contact: 'Contacte',
  email: 'E-mail',
  transport_lines: 'lignes',
  stations: 'Stations',
  property_sub_type: 'Sous type de bien', // 1
  file: 'fichier',
};

const filteredProperties = Object.keys(availableProperties);
const typeOfProperties = ['Appartement', 'Maison', 'Terrain', 'Annexe'];
module.exports = {
  propertiesHeader,
  filteredProperties,
  typeOfProperties,
};
