# base image
FROM node:alpine

ARG COOKIE_DOMAIN
ARG CLIENT_VIRTUAL_HOST
ARG CLIENT_VIRTUAL_PORT
ARG CLIENT_LETSENCRYPT_HOST
ARG CLIENT_LETSENCRYPT_EMAIL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_GEOLOCATION
ARG GOOGLE_MAIL_CLIENT
ARG GOOGLE_MAIL_SECRET
ARG JWT_SECRET
ARG MAIL_USER
ARG MONGO_URL_TEST
ARG MONGO_URL_PROD
ARG NEXT_PUBLIC_ROOT_URL
ARG NEXT_PUBLIC_UPLOAD_URL
ARG NODE_ENV
ARG PORT
ARG ROOT_URL
ARG SESSION_NAME
ARG SESSION_SECRET
ARG SENDGRID_API_KEY
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_TOKEN
ARG VIRTUAL_HOST

ENV COOKIE_DOMAIN=$COOKIE_DOMAIN
ENV CLIENT_VIRTUAL_HOST=$CLIENT_VIRTUAL_HOST
ENV CLIENT_VIRTUAL_PORT=$CLIENT_VIRTUAL_PORT
ENV CLIENT_LETSENCRYPT_HOST=$CLIENT_LETSENCRYPT_HOST
ENV CLIENT_LETSENCRYPT_EMAIL=$CLIENT_LETSENCRYPT_EMAIL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_GEOLOCATION=$GOOGLE_GEOLOCATION
ENV GOOGLE_MAIL_CLIENT=$GOOGLE_MAIL_CLIENT
ENV GOOGLE_MAIL_SECRET=$GOOGLE_MAIL_SECRET
ENV JWT_SECRET=$JWT_SECRET
ENV MAIL_USER=$MAIL_USER
ENV MONGO_URL_TEST=$MONGO_URL_TEST
ENV MONGO_URL_PROD=$MONGO_URL_PROD
ENV NEXT_PUBLIC_ROOT_URL=$NEXT_PUBLIC_ROOT_URL
ENV NEXT_PUBLIC_UPLOAD_URL=$NEXT_PUBLIC_UPLOAD_URL
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV ROOT_URL=$ROOT_URL
ENV SESSION_NAME=$SESSION_NAME
ENV SESSION_SECRET=$SESSION_SECRET
ENV SENDGRID_API_KEY=$SENDGRID_API_KEY
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
ENV TWILIO_TOKEN=$TWILIO_TOKEN
ENV VIRTUAL_HOST=$VIRTUAL_HOST
ENV VIRTUAL_PORT=$VIRTUAL_PORT




# create & set working directory
RUN mkdir -p /usr/src
WORKDIR /usr/src

# copy source files
COPY . /usr/src

# install dependencies
RUN npm install

# start app
RUN npm run build
EXPOSE 3000
CMD npm run start